version: '3.8'
services:
  php:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
#    command: composer install
    depends_on:
      - composer

  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
