name: CI

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1', '8.2']
    steps:
      - name: Set Environment Variables
        run: |
          echo "COMPANY_ID=${{ secrets.COMPANY_ID }}" >> $GITHUB_ENV
          echo "TENANT_USERNAME=${{ secrets.TENANT_USERNAME }}" >> $GITHUB_ENV
          echo "TENANT_PASSWORD=${{ secrets.TENANT_PASSWORD }}" >> $GITHUB_ENV
          echo "TENANT_NAME=${{ vars.TENANT_NAME }}" >> $GITHUB_ENV
          echo "TENANT_URL=${{ vars.TENANT_URL }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Check PHP Version
        run: php -v
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
      - run: echo "Composer dependencies have been installed"
      - name: Run Tests
        run: vendor/bin/phpunit
